# action.yaml
name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'

#inputs:
#  token:
#    description: "GitHub Token (env GITHUB_TOKEN)"
#    required: false
#    default: ${{ github.token }}
#  repository:
#    description: "GitHub repository name (env GITHUB_REPOSITORY)"
#    required: false
#    default: $${ env.GITHUB_REPOSITORY }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install toml
        pip install PyGithub

      shell: bash
    - name: Remove pre-release=true for volttron libs
      id: remove-pre-release-dependency
      run: python $GITHUB_ACTION_PATH/src/update_toml.py
      shell: bash
